#define EQUALS_CHECK  1
#define SEMICOLON 2
#define BOOLEAN 3
#define NUMBER 4
#define VARIABLE 5
#define LEFTPAR 6
#define RIGHTPAR 7
#define NOT 8
#define OPERATOR 9
#define CRLBRYCS 10
#define IF 11
#define ELSE 12
#define ELSE_IF 13
#define NOT_EQUALS_CHECK 14
#define ASSIGN_OPT 15
