#define EQUALS_CHECK  1
#define SEMICOLON 2
#define BOOLEAN 3
#define STRING 4
#define VARIABLES 5
#define LEFTPAR 6
#define RIGHTPAR 7
#define NOT 8
#define PRINT 9
#define CRLBRYCS 10
#define IF 11
#define ELSE 12
#define ELSE_IF 13
#define NOT_EQUALS_CHECK 14
#define ASSIGN_OPT 15
#define TYPE_BOOLEAN  16
#define TYPE_DOUBLE 17
#define TYPE_STRING 18
#define TYPE_INTEGER 19
#define COMMENT 20
#define AND 21
#define OR 22
#define ADD 23
#define SUB 24
#define MUL 25
#define DIV 26
#define INTEGER 27
#define DOUBLE 28
#define WHILE 29
#define FUNCTION 30
#define SWITCH 31
#define CASE 32
#define INPUT 33
#define WRITE 34
#define STDIN 35
#define STDOUT 36
#define CHARACTER 37
